Awesome books: plain JavaScript with objects
ryxtor/awesome-books pull request #1
Opened 2022-02-07 22:56 UTC by Obote

### What does this PR do?

- Create a collection that keeps a list of books (hint: you can use an array of objects for that).
- Create a function to add a new book to the collection, with title and author.
- Create a function to remove a book from the collection.
- Display all books saved in the collection in the top part of the page.
- Make sure that when a user clicks the "Add" button:
> - A new book is added to the collection.
> - The new book is displayed in the page.
- Make sure that when a user clicks the "Remove" button:
> - The correct book is removed from the collection.
> - The correct book disappears from the page.
- Make sure that data is preserved in the browser's memory by using localStorage.

2022-02-07 23:46 UTC, TedLivist requested changes
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @Obote and @ryxtor,

Good job so far!
✔️ Good documentation
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
#### _Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-07 23:46 UTC, TedLivist commented on script.js
> +// const bookList = document.querySelector('list');
- [ ] Kindly remove commented code as they make your codebase look messy, hard to read and maintain.

2022-02-07 23:46 UTC, TedLivist commented on script.js
> +  // eslint-disable-next-line no-use-before-define
- [ ] Linters help us write clean code. Let's maintain that. Kindly remove the linter disabling and resolve the resulting linter issue.

2022-02-07 23:46 UTC, TedLivist commented on script.js
> +  // console.log(bookCollection);
- [ ] Kindly remove commented code

2022-02-07 23:46 UTC, TedLivist commented on script.js
> +        localStorage.setItem('book-author', JSON.stringify(bookCollection));
- [ ] All changes should be persisted in the `localStorage`. As evidenced in the images below, when I remove a book, it is removed from the page, but not from the `localStorage`. This means that when I reload the page the books I removed return to the page (because it was not removed from the localStorage). Kindly fix this behavior.

  Books are added | Book is removed | Page is reloaded
  :---:|:---:|:---:
  ![otobe-1st](https://user-images.githubusercontent.com/36542986/152889590-baa80f65-286a-4c27-97ad-2d47eeea87a7.jpg) | ![otobe-2nd](https://user-images.githubusercontent.com/36542986/152889595-e0e95434-8ad9-4582-afe7-e1aa9a8b97e7.jpg) | ![otobe-3rd](https://user-images.githubusercontent.com/36542986/152889596-20e56031-de97-41be-8312-08d04296d67e.jpg)

2022-02-07 23:46 UTC, TedLivist commented on script.js
> +});
- [ ] I would recommend you extract this code for adding a book into a new function with that functionality.

  **SUGGESTION:** You can have implement the following code snippets:
  ```
  const addBook = () => {
    const inputs = new AwesomeBooks(inputTitle.value, inputAuthor.value, bookCollection.length + 1);
    bookCollection.push(inputs);
  };
  ```
  ```
  btnAdd.addEventListener('click', () => {
    addBook();
    localStorage.setItem('book_author', JSON.stringify(bookCollection));
    displayBooks();
  });
  ```

2022-02-08 15:12 UTC, Mihndim2020 approved these changes
# STATUS: APPROVED!!!  🎉 🎉 🎉 :champagne: :champagne: :champagne:
Hi @ryxtor, 

Your project is complete! Great work on making the changes requested by the previous reviewer. There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 :champagne: :champagne: :champagne:

![Congratulations-Memes-FEATURED](https://user-images.githubusercontent.com/65852621/133696300-b506e476-dc1a-443e-935a-c6f434e788b6.jpg)

## Optional suggestions

_Check the comments under the review._

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-08 15:15 UTC, merged